// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHLPnzzm-8XnKnDq_8-t0gTi-m8U4M_58',
    appId: '1:919490484685:web:fd3948611dc3f6d7ca8c84',
    messagingSenderId: '919490484685',
    projectId: 'relieflink-c903d',
    authDomain: 'relieflink-c903d.firebaseapp.com',
    storageBucket: 'relieflink-c903d.firebasestorage.app',
    measurementId: 'G-HTZM6CKKPZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCDSM0uHNr9CzQP7iAwO7263EER7F5ZjM',
    appId: '1:919490484685:android:d72921c84534f478ca8c84',
    messagingSenderId: '919490484685',
    projectId: 'relieflink-c903d',
    storageBucket: 'relieflink-c903d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtsUH2lCAr8qKF7y-j_-1JTB7-IKiFh7k',
    appId: '1:919490484685:ios:a6a777d19ac30fc1ca8c84',
    messagingSenderId: '919490484685',
    projectId: 'relieflink-c903d',
    storageBucket: 'relieflink-c903d.firebasestorage.app',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtsUH2lCAr8qKF7y-j_-1JTB7-IKiFh7k',
    appId: '1:919490484685:ios:a6a777d19ac30fc1ca8c84',
    messagingSenderId: '919490484685',
    projectId: 'relieflink-c903d',
    storageBucket: 'relieflink-c903d.firebasestorage.app',
    iosBundleId: 'com.example.hackathon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHLPnzzm-8XnKnDq_8-t0gTi-m8U4M_58',
    appId: '1:919490484685:web:5399adafb930d4cfca8c84',
    messagingSenderId: '919490484685',
    projectId: 'relieflink-c903d',
    authDomain: 'relieflink-c903d.firebaseapp.com',
    storageBucket: 'relieflink-c903d.firebasestorage.app',
    measurementId: 'G-Z786JFHQJD',
  );
}
